### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by MattLomb** [ashwinvaswani/whatif#14]
Hi,
I'm a  student approaching the world of Neural Networks and I was asked to go through your project, but I can't figure out how to run it. 
Could you help me please?

**Comment by ashwinvaswani** [comment]
Hi Matt,
Sure. Which part of the code were you having a difficulty with?

**Comment by MattLomb** [comment]
We're running the project but when we run the Deep Autoencoder Model, we get the following error: 'Failed to convert a NumPy array to a Tensor'
![error](https://user-images.githubusercontent.com/55020823/107653287-bfd63680-6c81-11eb-962e-b95d8902dcec.jpg)

**Comment by ashwinvaswani** [comment]
Can you send the full log trace?
